### ISSUE TITLE
Remove lines 258 and 259 of model_base ?

### ISSUE THREAD

**Issue by PatrickS97** [spjuhel/BoARIO#12]
Hi

After pip installing boario, Winerror 22 appeared for line 258 and 259 of model_base. 

To solve this problem I put these lines into an comment. 

As they do exactly the same thing as line 256 and 257, I did not observe any problem with that, but I did not find out if instead of putting these lines in a comment, the string location should be replaced

Patrick

**Comment by spjuhel** [comment]
Hi,

Thank you for raising an issue !

First, be aware, I haven't checked at all if the model run correctly on Windows, so you might discover more bugs. (I would suggest using the Windows Subsystem for Linux if you encounter too many problems).

Otherwise, you are right, this variable is unused, you can safely remove lines 258-259 eg:
https://github.com/spjuhel/BoARIO/blob/29596dd2e291a901d200735e450066c22076ee85/boario/model_base.py#L258-L259

(Note you can link lines from the repo by selecting them in the file in github (see https://i.stack.imgur.com/VK43g.gif)
